service: event-filter

frameworkVersion: '2'
provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
  environment:
    sqs_url: !Sub https://sqs.us-east-1.amazonaws.com/${AWS::AccountId}/espera-entrega
  eventBridge:
    useCloudFormation: true

functions:
  dynamoHandler:
    handler: handler.dynamoHandler
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:${AWS::AccountId}:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status
              
  enviaSqsHandler:
    handler: handler.enviaSqsHandler
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:us-east-1:${AWS::AccountId}:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status
            detail-type:
              - Alteracao Pizza
            detail:
              status:
                - pronto
                
  leSqsHandler:
    handler: handler.leSqsHandler
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - espera-entrega
          batchSize: 1
          maximumBatchingWindow: 60